version: '3.3'

services:
  fcc-project-urlshortener:
    build: .
    container_name: fcc-project-urlshortener
    restart: unless-stopped
    environment:
      NODE_ENV: development
    ports:
      - 3002:3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fcc-project-urlshortener.rule=Host(`fcc-project-urlshortener.app.honghong.me`)'
      - 'traefik.http.routers.fcc-project-urlshortener.entrypoints=https'
      - 'traefik.http.routers.fcc-project-urlshortener.service=fcc-project-urlshortener'
      - 'traefik.http.routers.fcc-project-urlshortener.tls.certresolver=cloudflare'
      - 'traefik.http.services.fcc-project-urlshortener.loadbalancer.server.port=3000'
    networks:
      - web

networks:
  web:
    external: true
